### PR TITLE
Merge Request for ui-docs

### PR DESCRIPTION
**Pull request by DevDhanadiya-2007**
Established Authentication and Added UI.

### CODE REVIEW

**Comment by Adiflickzzz** [comment]
Plz create a branch before creating a pull request ..

**Comment by DevDhanadiya-2007** [comment]
Ok you mean a separate branch other than main right?

**Comment by DevDhanadiya-2007** [comment]
> Plz create a branch before creating a pull request .. 
Ok you mean a separate branch other than main right?

**Comment by Adiflickzzz** [comment]
Yeah create a branch related to what you are working on and you then create a pr from that branch !!

**Comment by DevDhanadiya-2007** [comment]
Ok i will create a secondary feature branch and then make a pr to you.

**Comment by DevDhanadiya-2007** [comment]
Request you with a feature branch

**Pull request closed without merging**
